[package]
name = "type-fields-test"
version = "0.1.0"
edition = "2021"

[dependencies]
type-fields = { git = "https://github.com/bevy-rust-gpu/type-fields" }
type-fields-macros = { git = "https://github.com/bevy-rust-gpu/type-fields-macros" }
